spring.application.name=cinemaKiOsk

# .env \uD30C\uC77C\uC744 \uC124\uC815 \uD30C\uC77C\uB85C \uD3EC\uD568\uC2DC\uD0A4\uACA0\uB2E4\uB294 \uC120\uC5B8
spring.config.import=optional:file:.env[.properties]

# \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uAD00\uB828 \uC124\uC815
# MariaDB
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/cinema_kiosk
spring.datasource.username=task_master
spring.datasource.password=4444

# log4j2 \uC124\uC815
logging.level.org.springframework=info
logging.level.com.example.cinemakiosk=debug
# logging pattern
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

# jpa config
spring.jpa.hibernate.ddl-auto=update
## \uCFFC\uB9AC\uBB38 \uBCF4\uC5EC\uC8FC\uB294 \uC124\uC815
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
# JPA \uCD08\uAE30 INSERT \uC124\uC815
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:DB/data.sql
spring.jpa.defer-datasource-initialization=true

# mybatis
# \uB9E4\uD37C \uD30C\uC77C\uC758 \uC704\uCE58 (resources/mapper \uD3F4\uB354 \uB0B4\uC758 \uBAA8\uB4E0 xml \uC778\uC2DD)
mybatis.mapper-locations=classpath:mapper/**/*.xml
# \uCE74\uBA5C \uCF00\uC774\uC2A4 \uC790\uB3D9 \uB9E4\uD551
mybatis.configuration.map-underscore-to-camel-case=true
# \uD578\uB4E4\uB7EC \uC704\uCE58 \uC9C0\uC815 \uB9C8\uC774\uBC14\uD2F0\uC2A4 Enum\uD074\uB798\uC2A4 \uBCC0\uD658\uC744 \uC704\uD568
mybatis.type-handlers-package=com.example.cinemakiosk.handler

# sms
# apiKey
sms.api.key=${SMS_KEY}
# apiSecretKey
sms.api.secret=${SECRET_KEY}
# phone number
sms.api.phone=${PHONE}

# upload config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/whguswo/upload
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

# ??? ?? ?? (image save folder)
my.upload.path=C:/upload

# TMDB API
tmdb.api-key=${TMDB_API_KEY}
tmdb.base-url=https://api.themoviedb.org/3
tmdb.image-url=https://image.tmdb.org/t/p/w500


# JdbcTemplate? ?? ?? (SQL? ??)
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# ???? ??? ? ?? (StatementCreator ?)
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

# JSON \uC124\uC815 (\uB0A0\uC9DC \uBCC0\uD658 @JsonFormet)
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

# Spring Batch ??? ?? ??
spring.batch.jdbc.initialize-schema=always
# ???? ?? ? Spring Batch? ???? Job? ???? ?? ??
spring.batch.job.enabled=false

# JWT \uD0A4
jwt.cinema.secret.key=${JWT_KEY}